#!/usr/bin/env bash

# Path to this script
#FILE="${BASH_SOURCE[0]}"
#while [ -h "$FILE" ] ; do
#  SRC="$(readlink "$FILE")"
#  FILE="$( cd -P "$(dirname "$FILE")" && \
#           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
#done

#BX="~/basex"
BX="$( cd -P "$(dirname "$FILE")/.." && pwd )"
BXCORE="$( cd -P "$BX/../basex" && pwd )"

# API, core, and library classes
CP="$BX/BaseX.jar$(printf ":%s" "$BX/BaseX.jar" "$BX/lib/"*.jar "$BXCORE/target/classes" "$BXCORE/lib/"*.jar)"

# Options for virtual machine
VM=-Xmx512m

general_args=( )
vm_args=( )
while (( $# )) ; do
  if [[ $1 = "-X" ]] ; then
    vm_args+=( "$2" )
    shift 2
  else
    general_args+=( "$1" )
    shift
  fi
done

# Run code
echo java -cp "$CP" $VM "${vm_args[@]}" org.basex.BaseXHTTP "${general_args[@]}"


