#@echo off
echo Refreshing Frankenstein xLMNL ...
~/basex/bin/basex refresh-Frankenstein-xLMNL.xq

#echo ... Starting server ...
#start up BaseX server ...
#~/basex/bin/basexhttp -l

#start up Firefox ...
#xdg-open http://budgie:8984/Luminescent/
